/*
 * AnalizePresence.java
 *
 * Created on 06-mar-2012, 18:41:25
 */

package totalpos;

/**
 *
 * @author Saúl Hidalgo.
 */
public class AnalizePresence extends javax.swing.JInternalFrame {

    String storeName;
    String fromDate;
    String untilDate;

    /** Creates new form AnalizePresence */
    public AnalizePresence(String sn, String fd, String ud) {
        initComponents();
        this.storeName = sn;
        this.fromDate = fd;
        this.untilDate = ud;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        presenceTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        untilLabel = new javax.swing.JLabel();
        fromLabelDate = new javax.swing.JLabel();
        untilLabelDate = new javax.swing.JLabel();
        storeNameLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        send2ProfitButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Control de Asistencias y Horas Extras");

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        presenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Empleado", "Horas", "Bono Nocturno", "Bono de Asistencia", "Bono Produccion", "Dia 1"
            }
        ));
        presenceTable.setName("presenceTable"); // NOI18N
        presenceTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        presenceTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(presenceTable);

        titleLabel.setFont(new java.awt.Font("Courier New", 1, 18));
        titleLabel.setText("Control de Asistencias y Horas Extras");
        titleLabel.setName("titleLabel"); // NOI18N

        fromLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        fromLabel.setText("Nómina desde:");
        fromLabel.setName("fromLabel"); // NOI18N

        untilLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        untilLabel.setText("Hasta");
        untilLabel.setName("untilLabel"); // NOI18N

        fromLabelDate.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        fromLabelDate.setText("Nómina desde:");
        fromLabelDate.setName("fromLabelDate"); // NOI18N

        untilLabelDate.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        untilLabelDate.setText("Nómina desde:");
        untilLabelDate.setName("untilLabelDate"); // NOI18N

        storeNameLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        storeNameLabel.setText("Nómina desde:");
        storeNameLabel.setName("storeNameLabel"); // NOI18N

        closeButton.setText("Cerrar");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        send2ProfitButton.setText("Enviar a Profit");
        send2ProfitButton.setName("send2ProfitButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fromLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromLabelDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(untilLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(untilLabelDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storeNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(send2ProfitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(untilLabel)
                    .addComponent(fromLabelDate)
                    .addComponent(untilLabelDate)
                    .addComponent(storeNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(send2ProfitButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel fromLabelDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable presenceTable;
    private javax.swing.JButton send2ProfitButton;
    private javax.swing.JLabel storeNameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel untilLabel;
    private javax.swing.JLabel untilLabelDate;
    // End of variables declaration//GEN-END:variables

}
