/*
 * MainWindows.java
 *
 * Created on 08-jul-2011, 11:55:51
 */

package totalpos;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author shidalgo
 */
public class MainWindows extends javax.swing.JFrame {

    private User user;
    protected List<JFlowPanel> navegatorStack;

    /** Creates new form MainWindows
     * @param user 
     */
    public MainWindows(User user) {
        initComponents();
        this.user = user;
        navegatorStack = new LinkedList<JFlowPanel>();

        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        navegatorStack.add(createMenu(new Edge("root", "root", null, "")));
        showLast();
    }

    private JFlowPanel createMenu(Edge root){
        try {
            List<Edge> edges = ConnectionDrivers.listEdges(root.getId(), user.perfil);

            scrollPanel.getViewport().setView(null);
            JFlowPanel jPeople = new JFlowPanel();
            jPeople.applyComponentOrientation(getComponentOrientation());

            for (int i = 0; i < edges.size(); i++) {

                Edge ed = edges.get(i);

                JButton btn = new JButton(new AppUserAction(ed,this));
                btn.applyComponentOrientation(getComponentOrientation());
                btn.setFocusPainted(false);
                btn.setFocusable(false);
                btn.setRequestFocusEnabled(false);
                btn.setHorizontalAlignment(SwingConstants.CENTER);
                btn.setMaximumSize(new Dimension(150, 50));
                btn.setPreferredSize(new Dimension(150, 50));
                btn.setMinimumSize(new Dimension(150, 50));

                jPeople.add(btn);
            }
            JButton btn = new JButton(new AbstractAction() {

                public void actionPerformed(ActionEvent e) {
                    navegatorStack.remove(navegatorStack.size()-1);
                    showLast();
                }
            });
            btn.setText("Atras");
            btn.applyComponentOrientation(getComponentOrientation());
            btn.setFocusPainted(false);
            btn.setFocusable(false);
            btn.setRequestFocusEnabled(false);
            btn.setHorizontalAlignment(SwingConstants.CENTER);
            btn.setMaximumSize(new Dimension(150, 50));
            btn.setPreferredSize(new Dimension(150, 50));
            btn.setMinimumSize(new Dimension(150, 50));

            if ( ! root.getId().equals("root")){
                jPeople.add(btn);
            }

            return jPeople;

        } catch (SQLException ex) {
            MessageBox msg = new MessageBox(MessageBox.SGN_DANGER, "Error con la base de datos.", ex);
            msg.show(this);
            return null;
        } catch (Exception ex) {
            MessageBox msg = new MessageBox(MessageBox.SGN_DANGER, "Error", ex);
            msg.show(this);
            return null;
        }
    }

    private void showLast(){
        scrollPanel.getViewport().setView(navegatorStack.get(navegatorStack.size()-1));
    }

    private class AppUserAction extends AbstractAction {

        private Edge ed;
        private MainWindows mainWindows;

        private AppUserAction(Edge ed, MainWindows aThis) {
            this.ed = ed;
            this.mainWindows = aThis;

            putValue(Action.NAME, ed.getNombre());
            //putValue(Action.MNEMONIC_KEY,  new Integer(java.awt.event.KeyEvent.VK_A));
        }

        public void actionPerformed(ActionEvent evt) {
            if ( false ){

            }else{
                mainWindows.navegatorStack.add(createMenu(ed));
                mainWindows.showLast();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Constants.appName);

        scrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPanel.setName("scrollPanel"); // NOI18N
        scrollPanel.setPreferredSize(new java.awt.Dimension(510, 118));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables

}
