/*
 * ShowProfile.java
 *
 * Created on 18-jul-2011, 9:04:03
 */

package totalpos;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author shidalgo
 */
public class ShowProfile extends JDialog {

    /*protected DefaultTreeModel m_model;
    protected JTree  m_tree;

    private String profileId;
    protected MyJTree2ChangeProfile tree;
    protected JScrollPane jsp;*/

    private String profileId;

    


    /** Creates new form ShowProfile
     * @param parent
     * @param modal
     * @param profileId 
     */
    public ShowProfile(java.awt.Frame parent, boolean modal, String profileId) {
        super(parent);
        initComponents();

        this.setTitle("Ver / Modificar Perfil de " + profileId);

        this.profileId = profileId;
        
        /*DefaultMutableTreeNode root;
        root = exploreTree("/","root");

        setLayout(new BorderLayout());
        tree = new MyJTree2ChangeProfile(root,profileId,this);


        jsp = new JScrollPane((JTree)tree);
        add(jsp,BorderLayout.CENTER);


        tree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }

            private void tableKeyReleased(KeyEvent evt) {
                if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
                    setVisible(false);
                    dispose();
                }
            }
        });*/

        

        CheckNode cn = exploreTree("/", "root");

        String[] strs = {"swing",     // 0
		     "platf",     // 1
		     "basic",     // 2
		     "metal",     // 3
		     "JTree"};    // 4

        CheckNode[] nodes = new CheckNode[strs.length];
        for (int i=0;i<strs.length;i++) {
          nodes[i] = new CheckNode(strs[i]);
        }
        nodes[0].add(nodes[1]);
        nodes[1].add(nodes[2]);
        nodes[1].add(nodes[3]);
        nodes[0].add(nodes[4]);
        //nodes[3].setSelected(true);
        CheckNodeTreeExample cnte = new CheckNodeTreeExample(cn);
        cnte.setVisible(true);
        JTree tree = new JTree( nodes[0] );
        tree.setCellRenderer(new CheckRenderer());
        tree.getSelectionModel().setSelectionMode(
          TreeSelectionModel.SINGLE_TREE_SELECTION
        );
        tree.putClientProperty("JTree.lineStyle", "Angled");
        tree.addMouseListener(new NodeSelectionListener(tree));
        JScrollPane sp = new JScrollPane(tree);

        this.getContentPane().add(sp,    BorderLayout.CENTER);

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
