/*
 * ChangeIdleTime.java
 *
 * Created on 21-jul-2011, 12:53:57
 */

package totalpos;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author shidalgo
 */
public class ChangeIdleTime extends javax.swing.JDialog {

    public boolean isOk = false;
    /** Creates new form ChangeIdleTime
     * @param parent
     * @param modal
     */
    public ChangeIdleTime(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        String c = Shared.getConfig("idleTime");
        if ( c == null ) {
            return;
        }

        this.idleTimeTextField.setText( c );

        isOk = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        idleTimeTextField = new javax.swing.JTextField();
        secondsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Constants.appName);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        titleLabel.setText("Cambiar tiempo de autobloqueo");
        titleLabel.setName("titleLabel"); // NOI18N

        idleTimeTextField.setName("idleTimeTextField"); // NOI18N
        idleTimeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idleTimeTextFieldKeyPressed(evt);
            }
        });

        secondsLabel.setText("Milisegundos.");
        secondsLabel.setName("secondsLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(idleTimeTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondsLabel))
                    .addComponent(titleLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idleTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idleTimeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idleTimeTextFieldKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            try{
                long t = Long.valueOf(idleTimeTextField.getText());
                if ( t <= 10000 ){
                    MessageBox msb = new MessageBox(MessageBox.SGN_WARNING, "El tiempo no puede ser menor a 10 segundos.");
                    msb.show(null);
                    this.idleTimeTextField.setText( Shared.getConfig("idleTime") );
                }else{
                    try {
                        ConnectionDrivers.saveConfig("idleTime", t + "");
                        MessageBox msg = new MessageBox(MessageBox.SGN_SUCCESS, "Guardado correctamente");
                        msg.show(this);
                        ConnectionDrivers.initializeConfig();
                        this.dispose();
                    } catch (SQLException ex) {
                        MessageBox msg = new MessageBox(MessageBox.SGN_DANGER, "Error con la base de datos.", ex);
                        msg.show(this);
                    } catch (Exception ex) {
                        MessageBox msg = new MessageBox(MessageBox.SGN_DANGER, "Error", ex);
                        msg.show(this);
                        Shared.reload();
                    }
                }
            } catch ( NumberFormatException ex ){
                MessageBox msb = new MessageBox(MessageBox.SGN_WARNING, "El tiempo debe tener un formato válido.");
                msb.show(null);
                this.idleTimeTextField.setText( Shared.getConfig("idleTime") );
            }
        }
        if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            this.dispose();
        }
    }//GEN-LAST:event_idleTimeTextFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idleTimeTextField;
    private javax.swing.JLabel secondsLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
