/*
 * MainRetailWindows.java
 *
 * Created on 29-jul-2011, 15:41:13
 */

package totalpos;

import java.awt.SplashScreen;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shidalgo
 */
public final class MainRetailWindows extends javax.swing.JFrame {

    private User user;
    protected int quant = 1;
    private List<Item> items;
    public String actualId;
    FiscalPrinter printer;
    public boolean isOk = false;
    public boolean closing = false;
    public Double globalDiscount = .0;
    private Client client = null;
    private Assign assign;

    /** Creates new form MainRetailWindows
     * @param u
     * @param assign
     */
    public MainRetailWindows(User u, Assign assign) {
        try {
            initComponents();
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            user = u;
            printer = new FiscalPrinter();
            this.assign = assign;
            if ( !ConnectionDrivers.isAllowed(u.getPerfil(), "retail") ){
                MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Esta usuario no tiene permisos para utilizar el punto de venta.");
                msb.show(null);
                this.dispose();
                Shared.reload();
                return;
            }

            //createPhotoLabel();
            /*StartSplash ss = new StartSplash();
            ss.changeStatus("Verificando Impresora", 30);
            Shared.centerFrame(ss);
            ss.setVisible(true);*/
            updateAll();

            ConnectionDrivers.updateReportZ(printer.getZ());
            isOk = true;
        } catch (SQLException ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas con la base de datos.",ex);
            msb.show(null);
            this.dispose();
            Shared.reload();
        } catch (FileNotFoundException ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas en la comunicación con la impresora.",ex);
            msb.show(null);
            this.dispose();
            Shared.reload();
        } catch (Exception ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas en la comunicación con la impresora.",ex);
            msb.show(null);
            this.dispose();
            Shared.reload();
        } 
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    protected void updateAll() throws SQLException, FileNotFoundException, Exception{
        descriptionLabel.setText("Bievenido a Mundo Total");
        currentPrice.setText("");
        ivaLabelResult.setText("0.00 Bsf");
        TotalLabelResult.setText("0.00 Bsf");
        subTotalLabelResult.setText("0.00 Bsf");
        discountLabel.setVisible(false);
        discountResult.setVisible(false);
        items = new ArrayList<Item>();
        imageLabel.setVisible(false);
        globalDiscount = .0;

        updateTable();

        actualId = nextId();
        ConnectionDrivers.createReceipt(actualId, user.getLogin(), assign);
        setClient(null);
        printer.printerSerial = null;
        if (!checkPrinter()) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "La impresora no coincide con la registrada en el sistema. No se puede continuar");
            msb.show(null);
            this.dispose();
            Shared.reload();
        }
    }

    protected void updateTable(){
        DefaultTableModel model = (DefaultTableModel) gridTable.getModel();
        model.setRowCount(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try{
            wallpaper = new Bottom(ImageIO.read(new File("Fondo.jpg")));
            jPanel2 = new Bottom((new ImageIcon(getClass().getResource("/totalpos/resources/Factura.jpg"))).getImage());
            jScrollPane1 = new javax.swing.JScrollPane();
            gridTable = new javax.swing.JTable();
            barcodeField = new javax.swing.JTextField();
            subTotalLabelResult = new javax.swing.JLabel();
            subTotalLabel = new javax.swing.JLabel();
            discountLabel = new javax.swing.JLabel();
            discountResult = new javax.swing.JLabel();
            ivaLabelResult = new javax.swing.JLabel();
            ivaLabel = new javax.swing.JLabel();
            totalLabel = new javax.swing.JLabel();
            TotalLabelResult = new javax.swing.JLabel();
            jPanel1 = new Bottom((new ImageIcon(getClass().getResource("/totalpos/resources/Area-descripcion-articulo.jpg"))).getImage());
            descriptionLabel = new javax.swing.JLabel();
            currentPrice = new javax.swing.JLabel();
            imagePanel = new Bottom((new ImageIcon(getClass().getResource("/totalpos/resources/area-foto-articulo.jpg")).getImage()));
            imageLabel = new javax.swing.JLabel();
            jPanel6 = new javax.swing.JPanel();
            jPanel3 = new Bottom((new ImageIcon(getClass().getResource("/totalpos/resources/fecha-y-hora.jpg")).getImage()));
            whatTimeIsIt = new javax.swing.JLabel();
            messageToTheClients = new Bottom((new ImageIcon(getClass().getResource("/totalpos/resources/Area-mensajes-al-cajero.jpg")).getImage()));

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle(Constants.appName);
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    formWindowClosed(evt);
                }
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    formWindowClosing(evt);
                }
            });

        } catch( Exception ex){

        }
        wallpaper.setName("wallpaper"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gridTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripción", "Descuento", "Precio", "Iva", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridTable.setFocusable(false);
        gridTable.setName("gridTable"); // NOI18N
        gridTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(gridTable);
        gridTable.getColumnModel().getColumn(0).setPreferredWidth(300);

        barcodeField.setBorder(null);
        barcodeField.setName("barcodeField"); // NOI18N
        barcodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barcodeFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcodeFieldKeyReleased(evt);
            }
        });

        subTotalLabelResult.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        subTotalLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subTotalLabelResult.setFocusable(false);
        subTotalLabelResult.setName("subTotalLabelResult"); // NOI18N

        subTotalLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        subTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subTotalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/totalpos/resources/Etiquetas.jpg"))); // NOI18N
        subTotalLabel.setText("SubTotal:");
        subTotalLabel.setFocusable(false);
        subTotalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subTotalLabel.setName("subTotalLabel"); // NOI18N

        discountLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        discountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/totalpos/resources/Etiquetas.jpg"))); // NOI18N
        discountLabel.setText("Descuento:");
        discountLabel.setFocusable(false);
        discountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        discountLabel.setName("discountLabel"); // NOI18N

        discountResult.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        discountResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discountResult.setFocusable(false);
        discountResult.setName("discountResult"); // NOI18N

        ivaLabelResult.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        ivaLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ivaLabelResult.setFocusable(false);
        ivaLabelResult.setName("ivaLabelResult"); // NOI18N

        ivaLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ivaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ivaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/totalpos/resources/Etiquetas.jpg"))); // NOI18N
        ivaLabel.setText("I.V.A.(" + (Shared.getIva()+"").split("\\.")[0] + "%)");
        ivaLabel.setFocusable(false);
        ivaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ivaLabel.setName("ivaLabel"); // NOI18N

        totalLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/totalpos/resources/Etiquetas.jpg"))); // NOI18N
        totalLabel.setText("Total:");
        totalLabel.setFocusable(false);
        totalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        totalLabel.setName("totalLabel"); // NOI18N

        TotalLabelResult.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        TotalLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalLabelResult.setFocusable(false);
        TotalLabelResult.setName("TotalLabelResult"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(TotalLabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ivaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ivaLabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subTotalLabel)
                                    .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subTotalLabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(discountResult, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(barcodeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTotalLabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(subTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(discountResult, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(discountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ivaLabelResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(ivaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalLabel)
                    .addComponent(TotalLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        descriptionLabel.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setName("descriptionLabel"); // NOI18N

        currentPrice.setFont(new java.awt.Font("Courier New", 1, 24));
        currentPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentPrice.setName("currentPrice"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(currentPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        imagePanel.setName("imagePanel"); // NOI18N

        imageLabel.setName("imageLabel"); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel6KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1258, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel3.setName("jPanel3"); // NOI18N

        whatTimeIsIt.setName("whatTimeIsIt"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(whatTimeIsIt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(whatTimeIsIt, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        messageToTheClients.setFocusable(false);
        messageToTheClients.setName("messageToTheClients"); // NOI18N

        javax.swing.GroupLayout messageToTheClientsLayout = new javax.swing.GroupLayout(messageToTheClients);
        messageToTheClients.setLayout(messageToTheClientsLayout);
        messageToTheClientsLayout.setHorizontalGroup(
            messageToTheClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        messageToTheClientsLayout.setVerticalGroup(
            messageToTheClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout wallpaperLayout = new javax.swing.GroupLayout(wallpaper);
        wallpaper.setLayout(wallpaperLayout);
        wallpaperLayout.setHorizontalGroup(
            wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wallpaperLayout.createSequentialGroup()
                .addContainerGap(1090, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(wallpaperLayout.createSequentialGroup()
                .addGroup(wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wallpaperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wallpaperLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(messageToTheClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(83, 83, 83)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(wallpaperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        wallpaperLayout.setVerticalGroup(
            wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wallpaperLayout.createSequentialGroup()
                .addGroup(wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wallpaperLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(483, 483, 483))
                    .addGroup(wallpaperLayout.createSequentialGroup()
                        .addGroup(wallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(wallpaperLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(messageToTheClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barcodeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeFieldKeyReleased
        
    }//GEN-LAST:event_barcodeFieldKeyReleased

    private void barcodeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeFieldKeyPressed
        Shared.getScreenSaver().actioned();
        if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            logout();
            return;
        }else if ( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            try {
                List<Item> itemC = ConnectionDrivers.listItems(barcodeField.getText(), "", "", "");
                if ( itemC.isEmpty() ){
                    MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Artículo no existe!");
                    msb.show(this);
                    cleanForNewItem();
                    return;
                }
                assert( itemC.size() >= 1 );
                if ( itemC.get(0).isStatus() ){
                    MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Artículo bloqueado. No puede ser facturado!");
                    msb.show(this);
                    cleanForNewItem();
                    return;
                }

                if ( itemC.get(0).getCurrentStock() <= 0 ){
                    MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Este artículo no tiene stock. No se puede agregar.");
                    msb.show(this);
                    cleanForNewItem();
                    return;
                }
                addItem(itemC.get(0));
                updateCurrentItem();
                cleanForNewItem();
                updateSubTotal();
                
            } catch (SQLException ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                msb.show(this);
            } catch (Exception ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas al listar artículos.",ex);
                msb.show(this);
                this.dispose();
                Shared.reload();
            }
        } else if ( evt.getKeyCode() == KeyEvent.VK_DOWN ){
            if ( gridTable.getSelectedRow() == gridTable.getModel().getRowCount() - 1 ){
                return;
            }
            gridTable.setRowSelectionInterval(gridTable.getSelectedRow()+1, gridTable.getSelectedRow()+1);
            updateCurrentItem();
        } else if ( evt.getKeyCode() == KeyEvent.VK_UP ){
            if ( gridTable.getSelectedRow() <= 0 ){
                return;
            }
            gridTable.setRowSelectionInterval(gridTable.getSelectedRow()-1, gridTable.getSelectedRow()-1);
            updateCurrentItem();
        }else if ( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){
            Object[] options = {"Si",
                    "No"};
            int n = JOptionPane.showOptionDialog(this,
                "¿Desea eliminar el artículo?",
                Constants.appName,
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);

            if ( n == 0 ){
                deleteItem();
                if ( items.isEmpty() ){
                    try{
                        updateAll();
                    } catch (FileNotFoundException ex) {
                        MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                        msb.show(this);
                        this.dispose();
                        Shared.reload();
                    }
                    catch (SQLException ex) {
                        MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                        msb.show(this);
                        this.dispose();
                        Shared.reload();
                    } catch (Exception ex) {
                        MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                        msb.show(this);
                        this.dispose();
                        Shared.reload();
                    }
                }
            }
        } else if ( evt.getKeyCode() == KeyEvent.VK_F10 ){
            if ( items.isEmpty() ){
                return;
            }
            Object[] options = {"Si",
                    "No"};
            int n = JOptionPane.showOptionDialog(this,
                "¿Desea eliminar el pedido?",
                Constants.appName,
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
            if ( n == 0 ){
                deleteCurrent();
                try{
                    updateAll();
                } catch (SQLException ex) {
                    MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                    msb.show(this);
                    this.dispose();
                    Shared.reload();
                } catch (Exception ex) {
                    MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas al creando el pedido.",ex);
                    msb.show(this);
                    this.dispose();
                    Shared.reload();
                }
            }
        } else if ( evt.getKeyCode() == KeyEvent.VK_F11 ){
            toWait();
            try{
                updateAll();
            } catch (FileNotFoundException ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                msb.show(this);
                this.dispose();
                Shared.reload();
            } catch (SQLException ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                msb.show(this);
                this.dispose();
                Shared.reload();
            } catch (Exception ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
                msb.show(this);
                this.dispose();
                Shared.reload();
            } 
        } else if ( evt.getKeyCode() == KeyEvent.VK_F12 ){
            ListIdleReceipts lir = new ListIdleReceipts(this, true);
            if ( lir.isOk ){
                Shared.centerFrame(lir);
                lir.setVisible(true);
            }
        } else if ( evt.getKeyCode() == KeyEvent.VK_F8 ){
            ManageClient mc = new ManageClient(this, true);
            Shared.centerFrame(mc);
            mc.setVisible(true);
        } else if ( evt.getKeyCode() == KeyEvent.VK_F9 ){
            GlobalDiscount gd = new GlobalDiscount(this, true);
            Shared.centerFrame(gd);
            gd.setVisible(true);
        } else if ( evt.getKeyCode() == KeyEvent.VK_F5 ){
            try {
                if ( !items.isEmpty() ){
                    printer.printTicket(items, client, globalDiscount, actualId, user);
                    ConnectionDrivers.setFiscalData(actualId, printer.getSerial() , printer.getZ() , printer.getLastFiscalNumber());
                    if ( client != null ){
                        ConnectionDrivers.setClient(client,actualId);
                    }
                    ConnectionDrivers.setPritingHour(actualId);
                    ConnectionDrivers.finishReceipt(actualId);
                    updateAll();
                }
            } catch (Exception ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Error al imprimir!",ex);
                msb.show(null);
                this.dispose();
                Shared.reload();
            }
        } else if ( evt.getKeyCode() == KeyEvent.VK_F6 ){
            ExtractMoney em = new ExtractMoney(this, true, printer);
            Shared.centerFrame(em);
            em.setVisible(true);
        } /*else if ( evt.getKeyCode() == KeyEvent.VK_F7 ){
            try {
                printer.reportExtraction();
            } catch (Exception ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Error al imprimir!",ex);
                msb.show(null);
                this.dispose();
                Shared.reload();
            }
        }*/
    }//GEN-LAST:event_barcodeFieldKeyPressed

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseMoved
        Shared.getScreenSaver().actioned();
}//GEN-LAST:event_jPanel6MouseMoved

    private void jPanel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel6KeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            logout();
        }
}//GEN-LAST:event_jPanel6KeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        deleteCurrent();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        deleteCurrent();
    }//GEN-LAST:event_formWindowClosed

    private void updateCurrentItem(){
        Item i = items.get(gridTable.getSelectedRow());
        descriptionLabel.setText(i.getDescription());
        currentPrice.setText(i.getLastPrice().toString());
        Shared.loadPhoto(imageLabel, i.getImageAddr(),imagePanel.getWidth()-50,imagePanel.getHeight()-50);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalLabelResult;
    private javax.swing.JTextField barcodeField;
    private javax.swing.JLabel currentPrice;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel discountResult;
    private javax.swing.JTable gridTable;
    private javax.swing.JLabel imageLabel;
    public javax.swing.JPanel imagePanel;
    private javax.swing.JLabel ivaLabel;
    private javax.swing.JLabel ivaLabelResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel messageToTheClients;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel subTotalLabelResult;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel wallpaper;
    public javax.swing.JLabel whatTimeIsIt;
    // End of variables declaration//GEN-END:variables

    private void logout(){
        if ( JOptionPane.showConfirmDialog( (Shared.getMyMainWindows()) , "¿Está seguro que desea cerrar sesión?") == 0 ){
            deleteCurrent();
            Login l = new Login();
            Shared.centerFrame(l);
            Shared.maximize(l);
            l.setVisible(true);
            Shared.setUser(null);

            setVisible(false);
            dispose();
        }
    }

    private void addItem(Item get) {
        try {
            ConnectionDrivers.addItem2Receipt(actualId, get);
            DefaultTableModel model = (DefaultTableModel) gridTable.getModel();

            String[] s = {get.getDescription(), get.getDescuento(), get.getLastPrice().toString(), get.getLastPrice().getIva().toString(), get.getLastPrice().plusIva().toString()};
            model.addRow(s);
            gridTable.setRowSelectionInterval(model.getRowCount() - 1, model.getRowCount() - 1);
            items.add(get);
        } catch (SQLException ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas con la base de datos.",ex);
            msb.show(this);
            this.dispose();
            Shared.reload();
        } catch (Exception ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Problemas al agregar el artículo",ex);
            msb.show(this);
            this.dispose();
            Shared.reload();
        }
        
    }

    private void cleanForNewItem(){
        quant = 1;
        barcodeField.setText("");
    }

    public void updateSubTotal() {
        double subT = .0 , ivaT = .0 , total = .0 , subTwithoutD = .0;
        for (Item item : items) {
            subTwithoutD += item.getLastPrice().getQuant();
            subT += Shared.round( item.getLastPrice().getQuant()*(1.0-globalDiscount) , 2 );
            ivaT += item.getLastPrice().getIva().getQuant()*(1.0-globalDiscount);
            total += item.getLastPrice().plusIva().getQuant()*(1.0-globalDiscount);
        }

        subTotalLabelResult.setText(Constants.df.format(subTwithoutD) + " Bsf");
        if ( !globalDiscount.equals(.0) ){
            discountLabel.setText("Desc (" + Constants.df.format(globalDiscount*100.0) + "%):");
            discountLabel.setVisible(true);
            discountResult.setText(Constants.df.format(subT) + " Bsf");
            discountResult.setVisible(true);
        }else{
            discountLabel.setVisible(false);
            discountResult.setVisible(false);
        }
        
        ivaT = new Price(null, subT).getIva().getQuant();
        total = subT + ivaT;

        ivaLabelResult.setText(Constants.df.format(ivaT) + " Bsf");
        TotalLabelResult.setText(Constants.df.format(total) + " Bsf");
    }

    private String nextId(){
        try {
            int rightNow = ConnectionDrivers.lastReceiptToday();

            Date d = ConnectionDrivers.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
            return sdf.format(d)+ Constants.myId + String.format("%04d", rightNow);
        } catch (SQLException ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas con la base de datos.",ex);
            msb.show(this);
            this.dispose();
            Shared.reload();
            return "";
        } catch (Exception ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas al listar calcular el siguiente código de factura.",ex);
            msb.show(this);
            this.dispose();
            Shared.reload();
            return "";
        }
        
    }

    private void deleteItem() {
        if ( gridTable.getSelectedRow() != -1){
            try {
                ConnectionDrivers.deleteItem2Receipt(actualId, items.get(gridTable.getSelectedRow()));

                items.remove(gridTable.getSelectedRow());
                DefaultTableModel model = (DefaultTableModel) gridTable.getModel();
                model.removeRow(gridTable.getSelectedRow());
                if (items.isEmpty()) {
                    try {
                        ConnectionDrivers.cancelReceipt(actualId);
                        //MessageBox msb = new MessageBox(MessageBox.SGN_SUCCESS, "Pedido anulado.");
                        //msb.show(this);
                        //That msg might be annoying...
                    } catch (SQLException ex) {
                        MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas con la base de datos.",ex);
                        msb.show(this);
                        this.dispose();
                        Shared.reload();
                    }
                } else {
                    gridTable.setRowSelectionInterval(model.getRowCount() - 1, model.getRowCount() - 1);
                    updateCurrentItem();
                    updateSubTotal();
                    cleanForNewItem();
                }
            } catch (SQLException ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas con la base de datos.",ex);
                msb.show(this);
                this.dispose();
                Shared.reload();
            } catch (Exception ex) {
                MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas al eliminar artículo de la factura.",ex);
                msb.show(this);
                this.dispose();
                Shared.reload();
            }
        }else{
            MessageBox msb = new MessageBox(MessageBox.SGN_IMPORTANT, "Debe seleccionar un artículo.");
            msb.show(this);
        }
    }

    private void toWait() {
        try {
            if ( !items.isEmpty() ){
                ConnectionDrivers.putToIdle(actualId);
                MessageBox msb = new MessageBox(MessageBox.SGN_SUCCESS, "Pedido puesto en espera.");
                msb.show(this);
            }
        } catch (SQLException ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas con la base de datos.",ex);
            msb.show(this);
            this.dispose();
            Shared.reload();
        }
    }

    public void loadThisReceipt(Receipt r){
        if ( !r.getItems().isEmpty() ){
            actualId = r.getInternId();
            DefaultTableModel model = (DefaultTableModel) gridTable.getModel();

            for (Item item : r.getItems()) {
                String[] s = {item.getDescription(), item.getDescuento(), item.getLastPrice().toString(), item.getLastPrice().getIva().toString(), item.getLastPrice().plusIva().toString()};
                model.addRow(s);
                items.add(item);
            }
            gridTable.setRowSelectionInterval(model.getRowCount() - 1, model.getRowCount() - 1);
            updateCurrentItem();
            updateSubTotal();
        }
    }

    private boolean checkPrinter() throws SQLException, FileNotFoundException, Exception {
        String p = ConnectionDrivers.getMyPrinter();
        return printer.isTheSame(p);
    }

    public void deleteCurrent(){
        try {
            ConnectionDrivers.cancelReceipt(actualId);
            while (items != null && !items.isEmpty()) {
                deleteItem();
            }
        } catch (SQLException ex) {
            MessageBox msb = new MessageBox(MessageBox.SGN_DANGER, "Problemas con la base de datos.",ex);
            msb.show(this);
            this.dispose();
            Shared.reload();
        }
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public void setGlobalDiscount(Double d) throws SQLException{
        this.globalDiscount = d;
        updateSubTotal();
        ConnectionDrivers.setGlobalDiscount(actualId, d);
    }

}
