/*
 * ShowProfile.java
 *
 * Created on 18-jul-2011, 9:04:03
 */

package totalpos;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author shidalgo
 */
public class ShowProfile extends javax.swing.JDialog {

    protected DefaultTreeModel m_model;
    protected JTree  m_tree;

    private String profileId;
    protected MyJTree2ChangeProfile tree;
    protected JScrollPane jsp;


    /** Creates new form ShowProfile
     * @param parent
     * @param modal
     * @param profileId 
     */
    public ShowProfile(java.awt.Frame parent, boolean modal, String profileId) {
        super(parent, modal);
        initComponents();

        this.setTitle("Ver / Modificar Perfil de " + profileId);

        this.profileId = profileId;
        
        DefaultMutableTreeNode root;
        root = exploreTree("/","root");

        setLayout(new BorderLayout());
        tree = new MyJTree2ChangeProfile(root,profileId,this);


        jsp = new JScrollPane((JTree)tree);
        add(jsp,BorderLayout.CENTER);


        tree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }

            private void tableKeyReleased(KeyEvent evt) {
                if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
                    setVisible(false);
                    dispose();
                }
            }
        });
    }



    private DefaultMutableTreeNode exploreTree(String realName , String id){
        try {
            DefaultMutableTreeNode ans = new DefaultMutableTreeNode(
                    (!id.equals("root"))?(realName + " (" + id + ") " +
                    Shared.booleanToAllowed(ConnectionDrivers.isAllowed(profileId, id))):"/", true);

            for (Edge edge : ConnectionDrivers.listEdges(id)) {
                ans.add(exploreTree(edge.getNombre(),edge.getId()));
            }

            return ans;
        } catch (SQLException ex) {
            MessageBox msg = new MessageBox(MessageBox.SGN_DANGER, "Error", ex);
            msg.show(this);
            return null;
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ){
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
